import { mobileBrand } from "./mobileBrand";

export const teacherTheme = {
  bg: mobileBrand.canvas,
  pageBg: mobileBrand.canvas,
  header: mobileBrand.navy,
  topbar: mobileBrand.navy,
  surface: mobileBrand.surface,
  surface2: mobileBrand.surfaceMuted,
  active: mobileBrand.surfaceMuted,
  channel: mobileBrand.surfaceMuted,
  border: mobileBrand.border,
  border2: mobileBrand.borderStrong,
  text: mobileBrand.text,
  muted: mobileBrand.muted,
  dim: mobileBrand.dim,
  subtext: mobileBrand.muted,
  red: mobileBrand.red,
  blue: mobileBrand.navy,
  green: mobileBrand.success,
  purple: mobileBrand.info,
  amber: mobileBrand.warning,
  redSoft: mobileBrand.redSoft,
  redLine: mobileBrand.dangerBorder,
  redText: mobileBrand.red,
  blueSoft: mobileBrand.navySoft,
  blueLine: mobileBrand.infoBorder,
  greenSoft: mobileBrand.successSoft,
  greenLine: mobileBrand.successBorder,
  purpleSoft: mobileBrand.navySoft,
  amberSoft: mobileBrand.warningSoft,
  deepBlue: mobileBrand.navy,
  deepNavy: mobileBrand.navy,
} as const;
